FROM python:3.12-slim

WORKDIR /app
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

# системные либы для компиляции (минимум)
RUN apt-get update && apt-get install -y build-essential && rm -rf /var/lib/apt/lists/*

# ставим зависимости отдельно, чтобы кешировать
COPY requirements.txt .
RUN pip install -U pip && pip install -r requirements.txt watchfiles

# код будет примонтирован volume из compose
EXPOSE 8000
