"""Add unique constraint on monitor name per user

Revision ID: 95c952e131b7
Revises: 9914829570c1
Create Date: 2025-10-09 07:14:50.437593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95c952e131b7'
down_revision: Union[str, Sequence[str], None] = '9914829570c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_monitor_user_name', 'monitors', ['user_id', 'name'])
    op.drop_index(op.f('ix_users_tg_id'), table_name='users')
    op.create_unique_constraint(None, 'users', ['tg_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index(op.f('ix_users_tg_id'), 'users', ['tg_id'], unique=True)
    op.drop_constraint('uq_monitor_user_name', 'monitors', type_='unique')
    # ### end Alembic commands ###
